name: flutter_map_location_marker
description: A flutter map plugin for displaying device current location.
version: 6.0.0
repository: https://github.com/tlserver/flutter_map_location_marker
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^4.0.0
  latlong2: ^0.8.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.0.1

flutter:
